##Create a new user

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email":"dipendra.bista@cotiviti.com",
    "password":"admin@123"
}
###find single user
GET  http://localhost:3000/auth/signup?id=1