##Create a new user

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email":"punoj.bista@cotiviti.com",
    "password":"nepal@123"
}
###find single user
GET  http://localhost:3000/auth/6

###find all users with given email
GET  http://localhost:3000/auth?email=dipendra.bista@cotiviti.com

### delete user with given id
DELETE   http://localhost:3000/auth/5

### update user with given id
PATCH   http://localhost:3000/auth/5
Content-Type: application/json

{
    "email":"punojbista@gmail.com"
}